import "@/app/globals.css";
import type { Metadata } from "next";
// Import Swiper styles
import NavbarFooterWrapper from "@/components/layout/NavbarFooterWrapper";
import "swiper/css";

export const metadata: Metadata = {
  title: "NextBazaar - Ecommerce Website Template (Apparels)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={`antialiased`}>
        <NavbarFooterWrapper>{children}</NavbarFooterWrapper>
      </body>
    </html>
  );
}
