import "@/app/globals.css";
import type { Metadata } from "next";
import { Inter, Sora } from "next/font/google";
// Import Swiper styles
import NavbarFooterWrapper from "@/components/layout/NavbarFooterWrapper";
import ReduxProvider from "@/lib/ReduxProvider";
import "swiper/css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});

export const metadata: Metadata = {
  title: "NextBazaar - Ecommerce Website Template (Apparels)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${sora.variable}`}>
      <head></head>
      <body className={`antialiased`}>
        <ReduxProvider>
          <NavbarFooterWrapper>{children}</NavbarFooterWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}