import "@/app/globals.css";
import type { Metadata } from "next";
// Import Swiper styles
import "swiper/css";

export const metadata: Metadata = {
  title: "NextBazaar - Ecommerce Website Template (Apparels)",
  description: "Generated by create next app",
};

export default function shopRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="max-w-7xl mx-auto p-10 w-full mt-10">{children}</main>
  );
}
